package fortehackathon.entity;

public enum Role {
    PROJECT_MANAGER,
    SCRUM_MASTER,
    BACKEND_DEVELOPER,
    FRONTEND_DEVELOPER,
    QA,
    DESIGNER,
    ANALYST,

    PRODUCT_OWNER,
    PRODUCT_MANAGER,
    TEAM_LEAD,
    TECH_LEAD,
    DEVOPS_ENGINEER,
    SYSTEM_ARCHITECT,
    DATA_ENGINEER,
    DATA_SCIENTIST,
    ML_ENGINEER,
    MOBILE_DEVELOPER_ANDROID,
    MOBILE_DEVELOPER_IOS,
    FULLSTACK_DEVELOPER,
    BUSINESS_ANALYST,
    UX_UI_DESIGNER,
    SECURITY_ENGINEER,
    SUPPORT_ENGINEER,
    AUTOMATION_QA,
    MANUAL_QA
}
